# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Modern Work/DataScinces Course/Assignments/Data-Science Course Assignments ( By Mahmoud Ahmed Mohamed)/Assign-14 Extra/Scrapper_GUI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56,58, 89);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.lable_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.lable_title.setGeometry(QtCore.QRect(10, 0, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        self.lable_title.setFont(font)
        self.lable_title.setStyleSheet("color: rgb(254, 121, 199);")
        self.lable_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lable_title.setObjectName("lable_title")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(340, 24, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(90, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(50, 460, 551, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(98, 114, 164);    \n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254,121, 159, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(0, 490, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(90, 114, 164);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(20, 525, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(90, 114, 164);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.btn_scrap = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btn_scrap.setGeometry(QtCore.QRect(180, 120, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.btn_scrap.setFont(font)
        self.btn_scrap.setStyleSheet("background-color: rgb(98, 114, 164);    \n"
"color: rgb(225, 225, 225);\n"
"text-align: center;\n"
"border-style: none;\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.523, x2:0, y2:0.511364, stop:1 rgba(170, 85, 255, 255), stop:0 rgba(254,121, 159, 255));\n"
"")
        self.btn_scrap.setObjectName("btn_scrap")
        self.btn_close = QtWidgets.QPushButton(self.dropShadowFrame)
        self.btn_close.setGeometry(QtCore.QRect(612, 5, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("background-color: rgb(98, 114, 164);    \n"
"color: rgb(225, 225, 225);\n"
"text-align: center;\n"
"border-style: none;\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.523, x2:0, y2:0.511364, stop:1 rgba(170, 85, 255, 255), stop:0 rgba(254,121, 159, 255));\n"
"")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Modern Work/DataScinces Course/Assignments/Data-Science Course Assignments ( By Mahmoud Ahmed Mohamed)/Assign-14 Extra/Scrapper_GUI\\close_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(30, 30))
        self.btn_close.setObjectName("btn_close")
        self.combo_dir = QtWidgets.QComboBox(self.dropShadowFrame)
        self.combo_dir.setGeometry(QtCore.QRect(180, 320, 291, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_dir.sizePolicy().hasHeightForWidth())
        self.combo_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.combo_dir.setFont(font)
        self.combo_dir.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.combo_dir.setStyleSheet("background-color: rgb(98, 114, 164);    \n"
"color: rgb(225, 225, 225);\n"
"text-align: center;\n"
"border-style: none;\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.523, x2:0, y2:0.511364, stop:1 rgba(170, 85, 255, 255), stop:0 rgba(254,121, 159, 255));\n"
"")
        self.combo_dir.setObjectName("combo_dir")
        self.combo_dir.addItem("")
        self.combo_dir.addItem("")
        self.lable_title_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.lable_title_2.setGeometry(QtCore.QRect(200, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        self.lable_title_2.setFont(font)
        self.lable_title_2.setStyleSheet("color: rgb(90, 114, 164);")
        self.lable_title_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lable_title_2.setObjectName("lable_title_2")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lable_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Python</span> Scrapper</p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">books</span>.toscrape.com</p></body></html>"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p>Loading...</p></body></html>"))
        self.label_credits.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Created By :</span> Mahmoud Elemarati</p></body></html>"))
        self.btn_scrap.setText(_translate("MainWindow", "Start Scrapping"))
        self.combo_dir.setItemText(0, _translate("MainWindow", "Text Files"))
        self.combo_dir.setItemText(1, _translate("MainWindow", "SqlLite DataBase"))
        self.lable_title_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">Save as</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
